// src/components/driverhomepage/DH_navbar.jsx


export default function DH_navBar() {
  return (
    <nav className="flex justify-around bg-gray-800 p-4">
      {/* Home Icon */}
      <a
        routerLink="/"
        routerLinkActive="active"
        className="text-white hover:text-yellow-500"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="36"
          height="36"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="lucide lucide-house"
        >
          <path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" />
          <path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
        </svg>
      </a>

      {/* Earnings Icon */}
      <a
        routerLink="dh/earnings"
        routerLinkActive="active"
        className="text-white hover:text-yellow-500"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="36"
          height="36"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="lucide lucide-receipt"
        >
          <path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z" />
          <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8" />
          <path d="M12 17.5v-11" />
        </svg>
      </a>

      {/* Settings Icon */}
      <a href="#" className="text-white hover:text-yellow-500">
        <i className="icon settings-icon">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="36"
            height="36"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="lucide lucide-hand-platter"
          >
            <path d="M12 3V2" />
            <path d="M5 10a7.1 7.1 0 0 1 14 0" />
            <path d="M4 10h16" />
            <path d="M2 14h12a2 2 0 1 1 0 4h-2" />
            <path d="m15.4 17.4 3.2-2.8a2 2 0 0 1 2.8 2.9l-3.6 3.3c-.7.8-1.7 1.2-2.8 1.2h-4c-1.1 0-2.1-.4-2.8-1.2L5 18" />
            <path d="M5 14v7H2" />
          </svg>
        </i>
      </a>
    </nav>
  );
}

// src/app/driverHomepage/DH_navBar/DH_navBar.component.ts
import { Component, OnInit, Renderer2 } from '@angular/core';
import { ProfileComponent } from '../profile/profile.component';
import {NgIf, NgOptimizedImage} from '@angular/common'
import { EarningsComponent } from '../earnings/earnings.component';
import { Router, RouterLink, RouterLinkActive, RouterLinkWithHref, RouterOutlet } from '@angular/router';



@Component({
  selector: 'app-dh-navbar',
  standalone: true,
  imports: [RouterOutlet,RouterLink,RouterLinkActive,RouterLinkWithHref,ProfileComponent,NgIf,EarningsComponent,NgOptimizedImage],
  templateUrl: './DH_navBar.component.html',
  styleUrl: './DH_navBar.component.css'
})
export class DH_NavbarComponent {
  showPopup = false;

}


<router-outlet></router-outlet>

<nav class="navbar">
    <a routerLink="/" routerLinkActive="active" class="nav-item"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-house"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg></a>


    <a routerLink="dh/earnings" routerLinkActive="active" class="nav-item"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-receipt"><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 17.5v-11"/></svg> </a>
    <a href="#" class="nav-item"><i class="icon settings-icon"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-hand-platter"><path d="M12 3V2"/><path d="M5 10a7.1 7.1 0 0 1 14 0"/><path d="M4 10h16"/><path d="M2 14h12a2 2 0 1 1 0 4h-2"/><path d="m15.4 17.4 3.2-2.8a2 2 0 0 1 2.8 2.9l-3.6 3.3c-.7.8-1.7 1.2-2.8 1.2h-4c-1.1 0-2.1-.4-2.8-1.2L5 18"/><path d="M5 14v7H2"/></svg></i></a>
    <!-- <a (click)="toggleTheme()" class="nav-item theme-toggle">🌓</a> -->
</nav>
