// src/app/driverHomepage/driverHomepage/driverHomepage.component.ts
import { Component, OnInit } from '@angular/core';

import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { GoogleMapsModule } from '@angular/google-maps';
import { RideRequestsComponent } from '../rideRequests/rideRequests.component';


@Component({
  selector: 'app-driver-homepage',
  standalone: true,
  imports: [RideRequestsComponent,RouterOutlet,RouterLink,RouterLinkActive,GoogleMapsModule],
  templateUrl: './driverHomepage.component.html',
  styleUrl: './driverHomepage.component.css'
})
export class DriverHomepageComponent implements OnInit {


   map: google.maps.Map | undefined;
  markers: google.maps.Marker[] = [];

  ngOnInit(): void {
    this.initMap();
  }

  initMap(): void {
    // Use HTML5 Geolocation to get user's location
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        const userLocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };

        // Initialize the map with user's location as the center
        this.map = new google.maps.Map(document.getElementById('map') as HTMLElement, {
          center: userLocation,
          zoom: 14
        });

        // Add marker for user's location
        this.addMarker(userLocation, 'Your Location');

        // Fetch driver locations (replace with your actual API call)
        this.fetchDrivers(userLocation);
      });
    } else {
      console.error('Geolocation is not supported by this browser.');
    }
  }

  addMarker(position: google.maps.LatLngLiteral, title: string): void {
    const marker = new google.maps.Marker({
      position,
      map: this.map,
      title,
      animation: google.maps.Animation.DROP
    });
    this.markers.push(marker);
  }

  fetchDrivers(userLocation: google.maps.LatLngLiteral): void {
    // Example driver locations (replace with your actual API response)
    const drivers = [
      { lat: userLocation.lat + 0.01, lng: userLocation.lng + 0.01, name: 'Driver 1' },
      { lat: userLocation.lat - 0.01, lng: userLocation.lng - 0.01, name: 'Driver 2' }
    ];

    drivers.forEach(driver => {
      this.addMarker({ lat: driver.lat, lng: driver.lng }, driver.name);
    });
  }

  showRideRequest=true;
  earnings=54.32;
  center: google.maps.LatLngLiteral = { lat: 0, lng: 0 };
  zoom = 14;

}


<div id="map" style="height: 700px; width: 100%;">  <!-- Top bar -->
  
  <div class="top-bar">
    <div class="search-icon"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-menu"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg></div>
   <a routerLink="dh/earnings" routerLinkActive="active" class="nav-item"><div class="earnings-badge">
        {{earnings}}
  </div>  </a>
    <div  class="profile-pic">
      <a routerLink="dh/profile" routerLinkActive="active"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" color="black" class="lucide lucide-circle-user-round"><path d="M18 20a6 6 0 0 0-12 0"/><circle cx="12" cy="10" r="4"/><circle cx="12" cy="12" r="10"/></svg></a>
    </div>
  </div>



  <!-- Route indicator -->
  <div class="route-indicator">
    $8.50 for 3 miles
  </div>

  <!-- Central navigation icon -->
  <div class="navigation-icon">▲</div>
@if(showRideRequest){
  <app-ride-requests></app-ride-requests>
}
  <!-- Go button -->
  <div class="go-button">GO</div>

  <!-- Bottom bar -->
  <!-- <div class="bottom-bar">
  <div class ="blank"></div>
    <div class="status">You're offline</div>
    <div class="menu-icon"></div>
  </div> -->
</div>

// src/components/driverhomepage/DriverHomepage.jsx
export default function DriverHomepage({ earnings, showRideRequest }) {
  return (
    <div id="map" className="h-[700px] w-full relative">
      {/* Top bar */}
      <div className="absolute top-0 left-0 right-0 flex justify-between items-center bg-gray-800 text-white p-4">
        {/* Menu icon */}
        <div className="search-icon">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="36"
            height="36"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="lucide lucide-menu"
          >
            <line x1="4" x2="20" y1="12" y2="12" />
            <line x1="4" x2="20" y1="6" y2="6" />
            <line x1="4" x2="20" y1="18" y2="18" />
          </svg>
        </div>

        {/* Earnings */}
        <a
          routerLink="dh/earnings"
          routerLinkActive="active"
          className="text-yellow-400"
        >
          <div className="earnings-badge text-lg font-bold">{earnings}</div>
        </a>

        {/* Profile icon */}
        <div className="profile-pic">
          <a routerLink="dh/profile" routerLinkActive="active">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="36"
              height="36"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="lucide lucide-circle-user-round"
            >
              <path d="M18 20a6 6 0 0 0-12 0" />
              <circle cx="12" cy="10" r="4" />
              <circle cx="12" cy="12" r="10" />
            </svg>
          </a>
        </div>
      </div>

      {/* Route indicator */}
      <div className="absolute top-16 left-1/2 transform -translate-x-1/2 bg-white p-2 rounded-lg shadow-md">
        $8.50 for 3 miles
      </div>

      {/* Central navigation icon */}
      <div className="absolute bottom-1/2 left-1/2 transform -translate-x-1/2 translate-y-1/2 text-3xl text-green-500">
        ▲
      </div>

      {/* Ride request component */}
      {showRideRequest && <div className="absolute bottom-16 w-full"><app-ride-requests /></div>}

      {/* Go button */}
      <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 bg-green-500 text-white text-2xl font-bold px-6 py-3 rounded-full shadow-lg cursor-pointer">
        GO
      </div>
    </div>
  );
}
