// src/components/driverhomepage/Earnings.jsx
export default function Earnings() {
  return (
    <div className="container mx-auto p-4">
      {/* Header with back arrow and title */}
      <header className="flex items-center space-x-4 mb-4">
        <div className="back-arrow">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="36"
            height="36"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="lucide lucide-move-left"
          >
            <path d="M6 8L2 12L6 16" />
            <path d="M2 12H22" />
          </svg>
        </div>
        <div className="text-2xl font-bold">Daily</div>
      </header>

      {/* Date and Earnings (replace with dynamic content) */}
      <section className="date-earnings text-lg mb-4">
        {/* <div className="date">{{ today | date }} </div>
        <div className="earnings">{{ earnings | currency }}</div> */}
      </section>

      {/* Key Metrics */}
      <section className="metrics grid grid-cols-3 gap-4 mb-4 text-center">
        <div className="metric">
          <div className="value text-3xl font-bold">7</div>
          <div className="label text-sm text-gray-500">TRIPS</div>
        </div>
        <div className="metric">
          <div className="value text-3xl font-bold">{/* {onlineHours} */}4</div>
          <div className="label text-sm text-gray-500">ONLINE</div>
        </div>
        <div className="metric">
          <div className="value text-3xl font-bold">19</div>
          <div className="label text-sm text-gray-500">POINTS</div>
        </div>
      </section>

      {/* Earnings Breakdown */}
      <section className="earnings-breakdown mb-4">
        <div className="row flex justify-between py-2">
          <span>Trip Earnings</span>
          <span>$56.16</span>
        </div>
        <div className="row flex justify-between py-2">
          <span>Diamond Reward</span>
          <span>$2.62</span>
        </div>
        <div className="row flex justify-between py-2">
          <span>Toll</span>
          <span>$7.00</span>
        </div>
        <div className="row flex justify-between py-2">
          <span>Consecutive Trips Promotion</span>
          <span>$11.00</span>
        </div>

        <div className="row total flex justify-between py-2 font-bold border-t border-gray-300 mt-2 pt-2">
          <span>Total</span>
          <span>$76.78</span>
        </div>
      </section>

      {/* See Earnings Activity Button */}
      <div className="button-container text-center">
        <button className="earnings-button bg-green-500 text-white px-6 py-3 rounded-full hover:bg-green-600">
          SEE EARNINGS ACTIVITY
        </button>
      </div>
    </div>
  );
}

// src/app/earnings/earnings.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterLinkWithHref, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-earnings',
  standalone: true,
  imports: [RouterOutlet,RouterLink,RouterLinkActive,RouterLinkWithHref],
  templateUrl: './earnings.component.html',
  styleUrl: './earnings.component.css'
})
export class EarningsComponent {
  city="chennai"
  fare= 300;

  constructor(private router: Router){}

  navigateToHome(){
    this.router.navigate(['/']);
  }
}



<div class="container">
  <!-- Header with back arrow and title -->
  <header>
    <div (click)='navigateToHome()' class="back-arrow"><img src="../../assets/arrow_13494572.png" width="30" height="30"></div>
    <h1>Daily</h1>
  </header>

  <!-- Date and Earnings -->
  <section class="date-earnings">
    <div class="date">{{ today | date }} </div>
    <div class="earnings">{{ earnings | currency }}</div>
  </section>

  <!-- Key Metrics -->
  <section class="metrics">
    <div class="metric">
      <div class="value">7</div>
      <div class="label">TRIPS</div>
    </div>
    <div class="metric">
      <div class="value">{{ onlineHours }}</div>
      <div class="label">ONLINE</div>
    </div>
    <div class="metric">
      <div class="value">19</div>
      <div class="label">POINTS</div>
    </div>
  </section>

  <!-- Earnings Breakdown -->
  <section class="earnings-breakdown">
    <div class="row">
      <span>Trip Earnings</span>
      <span>$56.16</span>
    </div>
    <div class="row">
      <span>Diamond Reward</span>
      <span>$2.62</span>
    </div>
    <div class="row">
      <span>Toll</span>
      <span>$7.00</span>
    </div>
    <div class="row">
      <span>Consecutive Trips Promotion</span>
      <span>$11.00</span>
    </div>
    <hr>
    <div class="row total">
      <span>Total</span>
      <span>$76.78</span>
    </div>
  </section>

  <!-- See Earnings Activity Button -->
  <div class="button-container">
    <button class="earnings-button">SEE EARNINGS ACTIVITY</button>
  </div>
</div>
